### PR TITLE
Add V8 builtins, handle [native code]

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by xk** [comment]
Hi Brandon,

I've touched index.js last night, so I'm afraid it won't apply cleanly now. Could you please fix that ?

Thanks, 
Jorge.

**Comment by ghost** [comment]
I think it's good to go

**Comment by xk** [comment]
Brandon,

P.S.
But I still have no idea what's the deal with "native code" ... :-) would you mind to explain ?

**Comment by ghost** [comment]
Functions that will throw a syntax error when you try to run the code like: `function Object() { [native code] }`

I've actually made a significant rework of this that handles **proto** and some other stuff, but not sure if it's in the scope for what you want this to do. https://github.com/Benvie/JASON/tree/refactor if you're interested let me know.

**Comment by xk** [comment]
I see. So this:

process.setuid.toString()
'function () { [native code] }'

t.parse(t.stringify(process.setuid)).toString()
'function () { "[native code]"; }'

Won't throw, but (of course) the resulting object won't work either. That should be said in the reame.md.

It also ought to say something about the methods and the free vars (which are not captured). IOW the data in closures can't/won't be captured in the serialization.

Cool. Thanks.

**Comment by xk** [comment]
@bjouhier 

What do you think ?

**Comment by ghost** [comment]
In the forked version I have it actually attempt to do something useful. First, it tries to resolve the given object's global path so that it has an addressable path to it. Then it adds the function as:

```
  function someNative() {
    return global.path.to.the.object.apply(this, arguments)
  }
```

**Comment by bjouhier** [comment]
Sounds pretty clever to me.

First, this can be very useful when transferring objects between node "processes" (in this case, node's natives will be on both sides).. 

It can also help with threads if we want to support native addons in threads (fancy C/C++ libraries that do expensive computations).

And V8 has some interesting natives like WeakMaps and it may have more in the future. Makes sense to preserve them.

On the other hand, there will always be the problem with closure data. So it won't be perfect.

Gets my vote.

Bruno

**Comment by ghost** [comment]
My goal was to just make it pretty much 100% reliable in translating input into output that won't cause errors off the bat. This kind of thing will definitely need a higher level intermediate in all but the most pristine of conditions, due to the closure issue as you mentioned.

It's pretty cool serializing the entirety of a node process and copy pasting it into Chrome (and vice versa) and having that just work though. I had created a thing that did exactly this a few months back but the approach followed here is much more elegant and compact.

**Comment by bjouhier** [comment]
I did not think about going all the way to the browser. But this is pretty cool idea (over a secure channel of course).

**Comment by ghost** [comment]
My angle is from using Chromium/WebKit as the gui component for local applications, so security largely isn't an issue. Transparently binding between the view context and the controller context (in node) is the bigger concern so anything that minimizes the delta between the two ends is good.

**Pull request merged**
